### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by luvssti** [ebekker/blazor-ag-grid#1]
info :   GET https://api.nuget.org/v3-flatcontainer/blazoraggrid/index.json
info :   GET https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/blazoraggrid/index.json 769ms
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
info :   Unauthorized https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json 586ms
log  : Retrying 'FindPackagesByIdAsync' for source 'https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json'.
log  : Response status code does not indicate success: 401 (Unauthorized).
info :   GET https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
info :   Unauthorized https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json 575ms
log  : Retrying 'FindPackagesByIdAsync' for source 'https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json'.
log  : Response status code does not indicate success: 401 (Unauthorized).
info :   GET https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json
warn : Your request could not be authenticated by the GitHub Packages service. Please ensure your access token is valid and has the appropriate scopes configured.
info :   Unauthorized https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json 576ms
error: Failed to retrieve information about 'BlazorAgGrid' from remote source 'https://nuget.pkg.github.com/ebekker/download/blazoraggrid/index.json'.
error:   Response status code does not indicate success: 401 (Unauthorized).

**Comment by ebekker** [comment]
Ah, sorry!  I forgot you need to authenticate to GitHub Package Repo to get access.

Here's the detail:  [Configuring dotnet CLI for use with GitHub Packages](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-dotnet-cli-for-use-with-github-packages).

Note, I don't think you have to authenticate with your real GH creds, if I remember correctly, for public repos with public packages, you can provide a fake set of creds, and it should still work.  Real creds are only needed if you're trying to access a private repo or if you're trying to publish to it.

If you do go the "fake creds" route, let me know if it works for you, then I can update the README with more precise instructions.

**Comment by luvssti** [comment]
Thank You!
