### ISSUE TITLE
Question about getting data from a server

### ISSUE THREAD

**Issue by jhcorey** [ebekker/blazor-ag-grid#10]
Hello again,  
I am using some of your examples to populate the grid from a db server.

1) At first I started using FecthData3MemoryDS, which uses a class inheriting from IGridDatasource, but I ran into a number of issues using the column attributes.

2) Then I tried the example from FetchData2InlineVariable, which iterates through the array within the razor page html.  So far this is providing the functionality I need.

My question is, are there any issues with the simple method used in FetchData2InlineVariable?  It looks like you created FecthData3MemoryDS later, and I'm curious about whether this more elaborate coding was done to solve some problem.

Thanks!

**Comment by ebekker** [comment]
The 2 examples show different ways of retrieving and working with different sources of data.  One is not better than the other, they target different use cases.  In the InlineVariable scenario all of the data is available in memory at once.  In the MemoryDS scenario, the data is pulled dynamically, a page at a time from an external source via HTTP calls.

If you have a relatively small data set that can be all pulled it at once, go ahead and use the Inline approach, it will be faster and simpler.
