### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by ezzkht** [ebekker/blazor-ag-grid#3]
The grid is not refreshing when the data changes.
Manually calling **grid.Api.RedrawRows()** or **grid.Api.RefreshCells()** won't do the job either.

**Comment by ebekker** [comment]
Depending on how you're running this and what paging/caching behavior you have enabled, you may have to _purge_ the cached data.  Simply redrawing, just updates the DOM, and simply refreshing would still pull the data from cache if it's already been fetched.

The [online example](https://blog.bkkr.us/blazor-ag-grid/fetchdata-fetchds) has support for this "Purge Rows" feature which is implemented [here](https://github.com/ebekker/blazor-ag-grid/blob/master/src/examples/Example2/Pages/FetchData5MultiFetchDS.razor#L226).
