### ISSUE TITLE
Add inline

### ISSUE THREAD

**Issue by marll** [ebekker/blazor-ag-grid#7]
Hi,
is possible add row in inline mode?
Thanks

**Comment by ebekker** [comment]
[This](https://github.com/ebekker/blazor-ag-grid/blob/master/src/examples/Example2/Pages/FetchData1Inline.razor) example code produces [this](https://blog.bkkr.us/blazor-ag-grid/fetchdata-inline) result.

**Comment by ebekker** [comment]
If you mean, is it possible to add it dynamically, then I would suggest using a variable number of rows as shown in [this](https://github.com/ebekker/blazor-ag-grid/blob/master/src/examples/Example2/Pages/FetchData2InlineVariable.razor) example, then you control the backing model and can add/remove rows as necessary.
