### ISSUE TITLE
Custom display/edit components?

### ISSUE THREAD

**Issue by nj-db** [ebekker/blazor-ag-grid#8]
Hi,
Great work on this ag-grid wrapper. I was wondering if it is or will be possible to define custom components or controls for displaying & editing cell data?

**Comment by glazkovalex** [comment]
> Hi,
> Great work on this ag-grid wrapper. I was wondering if it is or will be possible to define custom components or controls for displaying & editing cell data?

Yes, of course, but not in this frozen project, but in my developing project [AgGrid.Blazor](https://github.com/glazkovalex/blazor-ag-grid)!
Here is an example of how this is done in the component [AgGrid.Blazor](https://github.com/glazkovalex/blazor-ag-grid) https://github.com/glazkovalex/blazor-ag-grid/blob/master/src/examples/Example3/Pages/FetchData5MultiFetchDS.razor.cs#L66
Mapping and implementation of ColorCellRenderer here: https://github.com/glazkovalex/blazor-ag-grid/blob/master/src/examples/Example3/wwwroot/Pages/ag-grid-script-config.ts#L14
